server:
  port: 9999
  servlet:
    context-path: /springboot1

debug: true

spring:
  http:
    encoding:
      charset: utf-8
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mybatis?useUnicode = true & characterEncoding = utf-8
    username: root
    password: 200076